all:
  children:
    k8s_cluster:
      children:
        k8s_masters:
          hosts:
            k8s-node:
              ansible_host: 10.10.10.10
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/vgio
    debian_nodes:
      children:
        storage_nodes:
          hosts:
            storage-node-1:
              ansible_host: 192.168.50.106
          vars:
            ansible_user: mr
            ansible_ssh_private_key_file: ~/.ssh/vgio
            # use pass for installation if key auth is not set up
            # ansible_ssh_pass: your_password_here
            # ansible_become_pass: your_password_here
        proxmox_nodes:
          hosts:
            proxmox-node-1:
              ansible_host: 192.168.50.4
          vars:
            ansible_user: root
            ansible_ssh_private_key_file: ~/.ssh/vgio
