apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret-sync
  namespace: database
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: secret/homelab/postgres
      property: password
