apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stirling-pdf-auth
  namespace: personal-services
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: stirling-pdf-auth
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: secret/homelab/stirling-pdf
      property: username
  - secretKey: password
    remoteRef:
      key: secret/homelab/stirling-pdf
      property: password
