apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uptime-kuma-admin
  namespace: personal-services
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: uptime-kuma-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: oracle-k3s/uptime-kuma
        property: admin_username
    - secretKey: password
      remoteRef:
        key: oracle-k3s/uptime-kuma
        property: admin_password
