- name: Update firewall rules on master nodes
  hosts: k8s_masters
  become: true
  tasks:
    - name: Allow Kubernetes API Server access (port 6443)
      community.general.ufw:
        rule: allow
        port: '6443'
        proto: tcp