apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vault-store.yaml
  - secrets.yaml
  - miniflux.yaml
  - rsshub.yaml
  - n8n.yaml
  - gateway.yaml
  - cloudflare-tunnel.yaml
